# Test environment credentials - safe to commit
active_record_encryption:
  primary_key: ci6DBmpWfMe2ZYSrzSZ5oRIi5ea6udXp
  deterministic_key: Xr9ieNekXQSTUmgtxkukgbYA0QXs3CIL
  key_derivation_salt: fsJRN0MJQUUdWo8zYoQmKymiZynWGqeB

# Test Google OAuth credentials (non-functional)
google:
  client_id: test_client_id
  client_secret: test_client_secret
  project_id: test_project