# Rails Best Practices configuration
# Allow some flexibility for modern Rails patterns

# Exclude certain directories
exclude_files: ['vendor/', 'db/', 'config/', 'test/']

# Allow certain warnings that are common in modern Rails
disable:
  - UseQueryAttributeCheck      # Modern Rails often uses direct attribute queries
  - UseModelAssociationCheck    # Can be overly strict with complex models
  - RemoveEmptyHelpersCheck     # Sometimes helpers are placeholders
  - RemoveTrailingWhitespaceCheck # Handled by other linters
  - AddModelVirtualAttributeCheck # Not always applicable
  - SimplifyRenderInControllersCheck # Can be overly pedantic