exclude_paths:
  - db/migrate
  - vendor
  - node_modules
  - test # Exclude test files from code smell analysis

# Note: Reek warnings don't fail the build since we use system() instead of system!()

detectors:
  IrresponsibleModule:
    exclude:
      - ActiveSupport::TestCase # Test helper extensions
      - ActionDispatch::IntegrationTest # Test helper extensions

  UncommunicativeVariableName:
    accept:
      - t # Common Rails migration variable
      - e # Exception variable
      - i # Iterator variable

  FeatureEnvy:
    exclude:
      - "*/db/migrate/*" # Migrations use table builder pattern
      - ActivitySchedulingService # Service objects work with domain objects
      - GoogleCalendarService # Service objects work with event data

  TooManyStatements:
    max_statements: 15 # Allow slightly more statements for migrations
    exclude:
      - "*/db/migrate/*"
      - HealthController # Health monitoring can have longer methods

  DuplicateMethodCall:
    exclude:
      - HealthController # Health monitoring often uses repetitive timing calculations
      - ActivitySchedulingService # Service objects may have repeated method calls for clarity

  UtilityFunction:
    public_methods_only: true # Only warn on public utility functions

  InstanceVariableAssumption:
    exclude:
      - "*Controller" # Rails controllers commonly use instance variables
      - "*/controllers/*" # All controller files use instance variables for views

  UncommunicativeMethodName:
    accept:
      - google_oauth2 # OAuth provider callback method name

  TooManyMethods:
    max_methods: 20 # Allow more methods for complex Rails classes

  TooManyInstanceVariables:
    exclude:
      - ActivitySchedulingService # Service objects may need multiple instance variables for complex operations

  TooManyStatements:
    max_statements: 25 # Allow more statements for complex service methods
    exclude:
      - ActivitySchedulingService # Service objects may have complex methods

  BooleanParameter:
    exclude:
      - ActivitySchedulingService # Service objects often use boolean flags for options

  ControlParameter:
    exclude:
      - ActivitySchedulingService # Service objects often have conditional behavior

  DataClump:
    exclude:
      - ActivitySchedulingService # Service objects may pass similar parameters to multiple methods

  RepeatedConditional:
    exclude:
      - AgendaProposedEvent # Domain objects may have repeated conditionals
      - HealthController # Health monitoring may check same conditions multiple times

  ManualDispatch:
    exclude:
      - ActivitySchedulingService # Service objects may use conditional dispatch patterns
      - HealthController # Health monitoring often uses dynamic method dispatch

  NestedIterators:
    exclude:
      - ActivitySchedulingService # Service objects may need nested iteration for complex operations
      - UserOnboardingService # Onboarding may need nested iteration for setup

  NilCheck:
    exclude:
      - "*" # Nil checks are defensive programming and acceptable in Rails